#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=00:30:00
#PBS -N 3Dfreesurfs
#PBS -V

rm -f finished
rm -rf surfaces

module load singularity 2> /dev/null

echo "converting aparc+aseg file"

time singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./convertfiles.sh"

echo "making surfaces"

singularity exec -e docker://brainlife/docker-pythonvtk ./main.py

count=$(ls surfaces/* | wc -l)

if [ "$count" == 87 ] 
then
	echo 0 > finished
else
	echo "files missing"
	echo 1 > finished
	exit 1
fi
